- src/java/com/articulate/sigma/KBmanager.java
These are just some small code cleanup type changes. There should be no features added or removed.
> Some small code cleanup.

- src/java/com/articulate/sigma/trans/THF.java
adapt it to the current version of the DB Manager.
> thf: fix the way to load the db

- build.xml
Ant files in other projects were re-indented earlier.
But sigmakee didn't have CI at that time so I didn't re-indent ant file in this project.
Now since CI is setup ant file can be re-indented to the same format.
> Reindent ant file

- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
`if (counter++ == 100) System.out.print(".");`
Produces output only once
I think intent was to print dot every hundredth formula
`if (counter++ % 100 == 0) System.out.print(".");`
I also added some additional info in debug statement:
- filename
- work done percentage
I needed filename cause I suspect tptp/fof file is produced twice.
> Add logging to SUMOKBtoTPTPKB

- .github/workflows/ant.yml
- .github/workflows/docker-publish.yml
- docker/sigma-ci/Dockerfile
- docker/sigmakee/Dockerfile
Also
- Update vampire to 4.8
- Set up CATALINA_OPTS to -Xmx10g
> Docker images for arm

- src/java/com/articulate/sigma/KBcache.java
- test/unit/java/com/articulate/sigma/KBcacheUnitTest.java
Diff seems to be quite simple so I changed few fields at once
- predicates
- transRels
- instRels
- instTransRels
> Replace KBcache fields types to Set

- src/java/com/articulate/sigma/KBcache.java
- insts
- valences
- disjoint
- disjointRelations
> Change KBcache fields tupes to interfaces

- INSTALL.MacOS
- README.md
- build.xml
- docker/sigma-ci/Dockerfile
- docker/sigmakee2018/README.md
- install.sh
- nbproject/ide-targets.xml
- nbproject/project.xml
Catch up all of sigmakee "readme" type files with latest build info based on updated Tomcat 9 & JDK 23. 
Updated java invocations for unit tests. 
Merged w/ head master.
All Unit and Integration tests SAT.
> Update all "readme" files with latest build info

- INSTALL.MacOS
- README.md
- build.xml
Also updated ReadMe concerning JDK version and to avoid JDK 17
> Ant Install task

- .github/workflows/ant.yml
- README.md
- build.xml
- docker/sigma-ci/Dockerfile
- docker/sigmakee/Dockerfile
- docker/sigmakee2018/Dockerfile
- docker/sigmakee2023/Dockerfile
- docker/sumo-ci/Dockerfile
Fix typo in install task
Update README.md
> Minor edits

- src/java/com/articulate/sigma/Formula.java
- src/java/com/articulate/sigma/KIF.java
Declare local vars outside of loops: Formula.java, add @Override annotations
> Streamlines

- INSTALL.MacOS
- README.md
- build.xml
> Updates to build and readme files

- README.md
- build.xml
- docker/sigma-ci/Dockerfile
- docker/sigmakee/Dockerfile
- docker/sumo-ci/Dockerfile
- nbproject/ide-targets.xml
1) build.xml - ensure perms on ~/Programs directory
2) update Readme.md
> Include z3 libs w/ vampire binary

- build.xml
- nbproject/ide-targets.xml
- test/integration/java/com/articulate/sigma/IntegrationTestBase.java
- test/unit/java/com/articulate/sigma/RowVarTest.java
- test/unit/java/com/articulate/sigma/SigmaTestBase.java
- test/unit/java/com/articulate/sigma/UnitTestBase.java
minor edits to update unit tests
> Seperate out an Ant task to update SUMO KBs to ~/.sigmakee

- src/java/com/articulate/sigma/DB.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/VerbNet/VerbNet.java
- src/java/com/articulate/sigma/dataProc/Hotel.java
- src/java/com/articulate/sigma/dataProc/WikiMuscle.java
- src/java/com/articulate/sigma/trans/DB2KIF.java
- src/java/com/articulate/sigma/wordNet/WSD.java
- src/java/com/articulate/sigma/wordNet/WordNet.java
- src/java/com/articulate/sigma/wordNet/WordNetUtilities.java
- test/integration/java/com/articulate/sigma/VerbNet/VerbNetTest.java
- test/integration/java/com/articulate/sigma/WSDwKBtest.java
Missed a few refactors on the last pull request. Discovered when compiling SigmaNLP
> Missed refactors for SigmaNLP to compile

- build.xml
- src/java/com/articulate/sigma/Formula.java
- src/java/com/articulate/sigma/VerbNet/VerbNet.java
- src/java/com/articulate/sigma/wordNet/WordNet.java
using System.err for error output. Easier to see on console (in red)
rename ant task for clarity
> Admin edits

- README.md
- nbproject/ide-targets.xml
- src/java/com/articulate/sigma/Clausifier.java
- src/java/com/articulate/sigma/Formula.java
- src/java/com/articulate/sigma/HTMLformatter.java
- src/java/com/articulate/sigma/KB.java
- src/java/com/articulate/sigma/KBcache.java
- src/java/com/articulate/sigma/tp/Vampire.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTFAKB.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
- src/java/com/articulate/sigma/trans/SUMOformulaToTPTPformula.java
- src/java/com/articulate/sigma/trans/SUMOtoTFAform.java
- src/java/com/articulate/sigma/trans/THF.java
- src/java/com/articulate/sigma/trans/THFnew.java
- src/java/com/articulate/sigma/trans/TPTP3ProofProcessor.java
- src/java/com/articulate/sigma/trans/TPTPutil.java
- src/java/com/articulate/sigma/wordNet/WordNetUtilities.java
- test/integration/java/com/articulate/sigma/trans/SUMOtoTFAKBTest.java
- test/unit/java/com/articulate/sigma/trans/SUMOformulaToTPTPformulaTest.java
- web/jsp/BrowseBody.jsp
- web/jsp/CommonHeader.jsp
- web/jsp/Diag.jsp
- web/jsp/Intersect.jsp
- web/jsp/Manifest.jsp
- web/jsp/TestStmnt.jsp
- web/jsp/WNDiag.jsp
Clicked everywhere I could find a link in the browser. Note to self, check the browser before submitting pull request.
> Correct errors in JSPs for Collections typing

- .github/workflows/ant.yml
- .github/workflows/docker-publish.yml
- build.xml
- config.xml
- docker/sigma-ci/Dockerfile
- docker/sigmakee/Dockerfile
- docker/sumo-ci/Dockerfile
- nbproject/build.properties
- nbproject/ide-targets.xml
- removeMath.sh
- src/java/com/articulate/sigma/KB.java
- src/java/com/articulate/sigma/KBmanager.java
- src/java/com/articulate/sigma/KIF.java
- src/java/com/articulate/sigma/tp/EProver.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTFAKB.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
- src/java/com/articulate/sigma/trans/TPTP3ProofProcessor.java
- src/java/com/articulate/sigma/trans/TPTPutil.java
- src/java/com/articulate/sigma/wordNet/OMWordnet.java
- test/integration/java/com/articulate/sigma/IntegrationTestBase.java
- test/integration/java/com/articulate/sigma/TPTP3Test.java
- test/integration/java/com/articulate/sigma/trans/SUMOtoTFAformTest.java
- test/unit/java/com/articulate/sigma/KBcacheUnitTest.java
- test/unit/java/com/articulate/sigma/UnitTestBase.java
- test/unit/java/com/articulate/sigma/trans/SUMOtoTFATest.java
- test/unit/java/com/articulate/sigma/trans/TPTP3ProofProcTest.java
- web/jsp/Prelude.jsp
Also, remaining refactors for negated_conjecture issue #13
> Fix image generation for proof during TPTP3ProofProcesser

- .github/workflows/ant.yml
- .github/workflows/docker-publish.yml
- docker/sigma-ci/Dockerfile
- removeMath.sh
- src/java/com/articulate/sigma/trans/TPTP3ProofProcessor.java
- test/integration/java/resources/config_all.xml
- test/integration/java/resources/config_topAndMid.xml
- test/integration/java/resources/config_topOnly.xml
- test/unit/java/resources/config_all.xml
- test/unit/java/resources/config_topAndMid.xml
- test/unit/java/resources/config_topOnly.xml
Some other fixes:
Correct name to proof image file
cross platform removeMath
> Correct paths in unit test configs

- README.md
- config.xml
- nbproject/ide-targets.xml
- nbproject/project.properties
- src/java/com/articulate/sigma/Graph.java
- src/java/com/articulate/sigma/trans/TPTP3ProofProcessor.java
- test/unit/java/com/articulate/sigma/GraphTest.java
- test/unit/java/com/articulate/sigma/UnitSigmaTestSuite.java
- test/unit/java/com/articulate/sigma/trans/TPTP3ProofProcTest.java
- test/unit/java/resources/config_all.xml
- test/unit/java/resources/config_topAndMid.xml
- test/unit/java/resources/config_topOnly.xml
- web/jsp/Graph.jsp
Turns out Process has a "wait" function
> Give process builder time to generate images

- src/java/com/articulate/sigma/Derivation.java
- src/java/com/articulate/sigma/KBmanager.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/PythonAPI.java
- src/java/com/articulate/sigma/nlg/NLGUtils.java
- src/java/com/articulate/sigma/wordNet/MultiWords.java
- src/java/com/articulate/sigma/wordNet/OMWordnet.java
- src/java/com/articulate/sigma/wordNet/WordNet.java
- src/java/com/articulate/sigma/wordNet/WordNetUtilities.java
- test/integration/java/com/articulate/sigma/VerbNet/IntegrationVerbNetTestSuite.java
- test/unit/java/com/articulate/sigma/wordNet/MultiWordsTest.java
- test/unit/java/com/articulate/sigma/wordNet/WordNetTest.java
Turns out, using the Multimap from Guava is not serializable. Have to use the JDK HashMap which is serializable
> Critical fix for Multiwords not being serialized with WordNet

- src/java/com/articulate/sigma/KB.java
Added KB.java utility to get ALL the termFormats and ALL the formats for a term.
> Added KB.java utility to get ALL the termFormats and ALL the formats for a term.

- .github/workflows/ant.yml
- build.xml
- docker/sigmakee/Dockerfile
- docker/sumo-ci/Dockerfile
- nbproject/ide-targets.xml
- nbproject/project.properties
- src/java/com/articulate/sigma/KBmanager.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/PasswordService.java
- src/java/com/articulate/sigma/nlg/NLGUtils.java
- src/java/com/articulate/sigma/wordNet/OMWordnet.java
- src/java/com/articulate/sigma/wordNet/WordNet.java
Will also aid the other web apps, SimgaRest and SigmaNLP, to shutdown cleaner
> Fixes for cleaner Tomcat shutdown

- .github/workflows/ant.yml
- INSTALL.MacOS
- README.md
- nbproject/ide-targets.xml
- nbproject/project.properties
- nbproject/project.xml
- src/java/com/articulate/sigma/KB.java
- test/unit/java/com/articulate/sigma/KBTest.java
Add two new unit test (thanks Rich)!
> Minor proj. file edits

- src/java/com/articulate/sigma/KBmanager.java
New addition of imageFormat prop
> Update the KB CONFIG_KEYS

- .github/workflows/ant.yml
- build.xml
- config.xml
- docker/sigmakee/Dockerfile
- nbproject/ide-targets.xml
- src/java/com/articulate/sigma/HTMLformatter.java
- src/java/com/articulate/sigma/KBmanager.java
- test/integration/java/resources/config_all.xml
- test/integration/java/resources/config_topAndMid.xml
- test/integration/java/resources/config_topOnly.xml
- test/unit/java/resources/config_all.xml
- test/unit/java/resources/config_topAndMid.xml
- test/unit/java/resources/config_topOnly.xml
Will speed up initial usage of the docker image
dedicated path to jedit in config.xml
> For the sigmakee docker image, start with only top, mid and english ontologies in config.xml

- VerifyInstallationPrerequisites.sh
Script verifies that pre-requisites have been installed and environment variables have been set.
> Add script to verify that pre-requisites

- .github/workflows/ant.yml
Sorry, it was late last night to get this thing working.
> Yaml syntax correction

- src/java/com/articulate/sigma/KB.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/tp/Vampire.java
- src/java/com/articulate/sigma/trans/SUMOformulaToTPTPformula.java
- src/java/com/articulate/sigma/trans/SUMOtoTFAform.java
- src/java/com/articulate/sigma/trans/TPTP3ProofProcessor.java
- test/integration/java/com/articulate/sigma/trans/TPTP2SUMOTest.java
- test/unit/java/com/articulate/sigma/FormulaUtilTest.java
- test/unit/java/com/articulate/sigma/KButilitiesTest.java
- test/unit/java/com/articulate/sigma/trans/SUMOformulaToTPTPformulaTest.java
> Fix for class/type error checking

- docker/sumo-ci/Dockerfile
- nbproject/ide-targets.xml
- src/java/com/articulate/sigma/CELTTestSuite.java
- src/java/com/articulate/sigma/KB.java
- src/java/com/articulate/sigma/KBcache.java
- src/java/com/articulate/sigma/KBmanager.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
- test/integration/java/com/articulate/sigma/KBcacheTest.java
- test/unit/java/com/articulate/sigma/trans/SUMOtoTFATest.java
- web/jsp/AddConstituent.jsp
- web/jsp/Properties.jsp
Frame in place to optimize cache building
Fix some typos
> SUMO-CI image requires an entry point when using straight ubuntu

- docker/sumo-ci/Dockerfile
> Turns out we need tomcat as the runner for sumo-ci

- doc/com/articulate/sigma/nlg/LanguageFormatter.html
- doc/manual/SigmaManual.tex
- src/java/com/articulate/sigma/nlg/LanguageFormatter.java
- test/unit/java/com/articulate/sigma/nlg/LanguageFormatterTest.java
Added support for question formatting.
> Thompson_2025_04_15

- src/java/com/articulate/sigma/KB.java
- src/java/com/articulate/sigma/KBcache.java
- src/java/com/articulate/sigma/KBmanager.java
- test/integration/java/com/articulate/sigma/KBmanagerInitIntegrationTest.java
Negligible time savings and introduced an out of order/race
> revert back to sequential processing of adding constituents  to the KB

- nbproject/ide-targets.xml
- nbproject/project.xml
- test/integration/java/com/articulate/sigma/TPTP3Test.java
For whatever reason, the bindings on the GitHub runner show as [Abstract], while on local macOS [Class]
> Fix TPTP3Test.testE to be more generic with test results

- docker/sumo-ci/Dockerfile
> We'll need Ant in sumo-ci now

- src/java/com/articulate/sigma/Diagnostics.java
This method is still in progress and currently extracts the variables from the formula.
> added getVariableLinks() method

- src/java/com/articulate/sigma/Diagnostics.java
Diagnostics.java has three hard coded formulas that works for variable co-occurrences. File pipeline is work in progress.
> Update for Diagnostics.java

- src/java/com/articulate/sigma/trans/SUMOKBtoTFAKB.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
GitHub workflow was hanging again
> Shutdown the executor service after TPTP/FOF/TFF translation

- src/java/com/articulate/sigma/Formula.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTFAKB.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
- src/java/com/articulate/sigma/trans/TPTPutil.java
To many mains expected a clean JVM exit, esp. TPTP3ProofProcessor which was hanging on GitHub workflow
> Parallel threading has to be daemon

- src/java/com/articulate/sigma/Diagnostics.java
- src/java/com/articulate/sigma/FormulaPreprocessor.java
- src/java/com/articulate/sigma/KButilities.java
- src/java/com/articulate/sigma/KifCheckWorker.java
- src/java/com/articulate/sigma/KifFileCheckServlet.java
- src/java/com/articulate/sigma/KifFileChecker.java
- src/java/com/articulate/sigma/PasswordService.java
- src/java/com/articulate/sigma/PredVarInst.java
- src/java/com/articulate/sigma/trans/SUMOKBtoTPTPKB.java
- web/jsp/CheckKifFile.jsp
- web/jsp/CommonHeader.jsp
Added to Kif File Checker: User guard, File size limit, Queue based sequential processing, Formula line finder
> Rose 9 8 2025
